### PR TITLE
add svenja to the participants list

### PR DESCRIPTION
**Pull request by svenjawagner**
I would like to join the RheinMain Tech Cabal - thanks :)

### CODE REVIEW

**Comment by coderbyheart** [comment]
💶 payment missing.

**Comment by coderbyheart** [comment]
And I think @viddity and @Silvia77 might vouch for you?

**Comment by Silvia77** [comment]
Yes, I vouch gladly 😄

**Comment by viddity** [comment]
Most def :-)

**Comment by svenjawagner** [comment]
yeah thanks :) and I did the payment.

**Comment by coderbyheart** [comment]
:euro: payment received!

**Pull request merged**
