### PR TITLE
Attend rheinmain tech cabal

### PR DESCRIPTION
**Pull request by BridgeAR**
Reference @junedev

### CODE REVIEW

**Comment by coderbyheart** [comment]
Yes, and I can vouch for you, too ;-)

**Comment by junedev** [comment]
I hereby also vouch for @BridgeAR ... is that enough or do I have to list why I think he is valuable participant? ;-)

**Comment by coderbyheart** [comment]
@junedev are you coming, too?

**Comment by coderbyheart** [comment]
:dollar: Payment is missing.

**Comment by junedev** [comment]
@coderbyheart I just signed up.

**Comment by coderbyheart** [comment]
Did not attend.

**Pull request closed without merging**
